spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-92-151-217.compute-1.amazonaws.com/d345fgkn7he9u0
  username: bwwcftwbawcfng
  password: a5ec7adb425730bbcbc7b6eb5ca982880a8e4bdf54347cd1a35c665bde0064bc
  platform: postgres
  driver-class-name: org.postgresql.Driver

spring:
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    url: redis://:pf34f21243ff91a3d4fada03dbaed9e363631e4945e4314bec3b44a35ceea8c23@ec2-54-145-215-74.compute-1.amazonaws.com:24709

jwt:
  token:
    secretKey : hyunbenny_sns_app_2023_04_17_151600.secret_key
    expiredMs : 2592000000
